--- 
title: "Primer on replication, preregistration and open science through browser-based experiments in _magpie"
author: "Michael Franke"
date: "Last compiled: `r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["references.bib"]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is the material for a course on implementation, design and deployment of browser-based experiments using _magpie, as part of ESSLLI 2019 (Riga, Latvia)."
---

# About this book

Experimental work is hard. Opportunities for suboptimality and failure abound. This course is all about avoiding pitfalls and cultivating a mindset aimed at continually improving practices. We will execute the whole process of implementation, execution and data analysis during this course, based on a replication of an existing experiment, which we will preregister. We do this using [\_magpie](https://magpie-ea.github.io/magpie-site/index.html), an architecture to help realize browser-based experiments.

This is the material for a course taught at ESSLLI 2019 (Riga, Latvia).

Can I insert a reference to @Rbase?

<!--chapter:end:index.Rmd-->


# Potential problems with empirical science {#empirical-research}

Placeholder


## Objective evidence
## Observation vs. manipulation
## The publication-generating process
## Researcher degrees of freedom

<!--chapter:end:02-problems-empirical-science.Rmd-->


# Countermeasures

Placeholder


## Direct replication
## Preregistration
## Open Science

<!--chapter:end:03-countermeasures.Rmd-->

# Methods

We describe our methods in this chapter.

<!--chapter:end:04-git.Rmd-->

# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

## Example two

<!--chapter:end:05-magpie-basics.Rmd-->

# Final Words

We have finished a nice book.

<!--chapter:end:06-adams-family.Rmd-->

# Final Words

We have finished a nice book.

<!--chapter:end:07-magpie-deployment.Rmd-->

